version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    working_directory: ~/sunbird-video-player
    docker:
     - image: cimg/node:20.4.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install    
      - checkout:
          path: ~/sunbird-video-player
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install dependecies and audit for critical 
          command: cd projects/sunbird-video-player &&  npm install --no-progress --legacy-peer-deps && npx audit-ci@^6 --config ./audit-ci.jsonc && rm -rf node_modules
      - run:
          name: ng lint
          command: cd ~/sunbird-video-player && npm install --no-progress --legacy-peer-deps  && npm run lint
      - run:
          name: Executing test cases
          command: npm run test -- --no-watch
      - run: 
          name: Install sonar scanner
          command: 'sudo npm install -i -g sonarqube-scanner'
      - run: 
          name: Sonar scanner
          command: cd ~/sunbird-video-player && sonar-scanner 
      - run:
          name: Publish Web component to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-web-component && npm pack ./web-component
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm publish project-sunbird-sunbird-video-player-web-component-* --access public
            else
              npm run build-web-component && npm pack ./web-component
            fi 
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-lib && npm pack ./dist/sunbird-video-player
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm publish project-sunbird-sunbird-video-player-v9-*
            else
              npm run build-lib && npm pack ./dist/sunbird-video-player
            fi
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
